basePath: /
consumes:
- application/json
host: localhost:8080
info:
  contact:
    email: umermasood.dev@gmail.com
    name: M Umer Masood
    url: https://github.com/umermasood
  description: This is the Recipe API
  title: Recipes API
  version: 1.0.0
paths:
  /recipes:
    get:
      description: Returns list of recipes
      operationId: listRecipes
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
      tags:
      - recipes
    post:
      description: Create a new recipe
      operationId: newRecipe
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid input
      tags:
      - recipes
  /recipes/{id}:
    delete:
      description: Delete an existing recipe
      operationId: deleteRecipe
      parameters:
      - description: ID of the recipe
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
        "404":
          description: Invalid recipe ID
      tags:
      - recipes
    put:
      description: Update an existing recipe
      operationId: updateRecipe
      parameters:
      - description: ID of the recipe
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid input
        "404":
          description: Invalid recipe ID
      tags:
      - recipes
  /recipes/search:
    get:
      description: Search recipes based on tags
      operationId: findRecipe
      parameters:
      - description: recipe tag
        in: query
        name: tag
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
      tags:
      - recipes
produces:
- application/json
schemes:
- http
swagger: "2.0"
